/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
	nodes: {
		BendWallTop: THREE.Mesh
	}
	materials: {
		["Material.431"]: THREE.MeshStandardMaterial
	}
}

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF("/BendWallTop.glb") as GLTFResult
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh geometry={nodes.BendWallTop.geometry} material={materials["Material.431"]} scale={[-0.5, -0.5, 0.5]} />
		</group>
	)
}

useGLTF.preload("/BendWallTop.glb")
