/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
	nodes: {
		Connector: THREE.Mesh
	}
	materials: {}
}

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF("/Connector.glb") as GLTFResult
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh geometry={nodes.Connector.geometry} material={nodes.Connector.material} scale={0.2} />
		</group>
	)
}

useGLTF.preload("/Connector.glb")
