/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
	nodes: {
		Corner_4: THREE.Mesh
	}
	materials: {
		["Material.070"]: THREE.MeshStandardMaterial
	}
}

export default function Corner_4({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF("/Corner_4.glb") as GLTFResult
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				geometry={nodes.Corner_4.geometry}
				material={materials["Material.070"]}
				scale={0.5}
				position={[0.5, 0.5, 0.5]}
			/>
		</group>
	)
}

useGLTF.preload("/Corner_4.glb")
