/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
	nodes: {
		FlatStairsFreeUper: THREE.Mesh
	}
	materials: {
		["Material.146"]: THREE.MeshStandardMaterial
	}
}

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF("/FlatStairsFreeUper.glb") as GLTFResult
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh geometry={nodes.FlatStairsFreeUper.geometry} material={materials["Material.146"]} scale={[1, 1, 0.13]} />
		</group>
	)
}

useGLTF.preload("/FlatStairsFreeUper.glb")
