/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
	nodes: {
		StairB_3: THREE.Mesh
	}
	materials: {
		["Material.028"]: THREE.MeshStandardMaterial
	}
}

export default function StairB_3({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF("/StairB_3.glb") as GLTFResult
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				geometry={nodes.StairB_3.geometry}
				material={materials["Material.028"]}
				scale={0.5}
				position={[0.5, 0.5, 0.5]}
			/>
		</group>
	)
}

useGLTF.preload("/StairB_3.glb")
