/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"
import { MathUtils } from "three"

type GLTFResult = GLTF & {
	nodes: {
		Tube: THREE.Mesh
	}
	materials: {
		["Material.078"]: THREE.MeshStandardMaterial
	}
}

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF("/Tube.glb") as GLTFResult

	return (
		<group ref={group} {...props} dispose={null}>
			<mesh geometry={nodes.Tube.geometry} material={materials["Material.078"]} scale={0.5} />
		</group>
	)
}

useGLTF.preload("/Tube.glb")
